#!/usr/bin/env bash
# installs nginix on the server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

# # Test Nginx configuration
# sudo nginx -t

# Reload Nginx to apply the new configuration
sudo service nginx restart