#!/usr/bin/env bash
# Script configuring nginx in my server

sudo apt update -y
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
