#!/usr/bin/env bash
# installs nginix on the server
# Configure your Nginx server so that /redirect_me is redirecting to another page

REDIRECT="location /redirect_me {\n\n\t\t return 301 https://www.youtube.com;\n\t}"

# Update the package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# sudo sed -i "47i $REDIRECT" /etc/nginx/sites-available/default
sudo sed -i "0,/location/s|location|$REDIRECT\n\t&|" /etc/nginx/sites-available/default

# Reload Nginx to apply the new configuration
sudo service nginx restart
