#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header "X-Served-By"

sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i "/server_name _;/a \\\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
