#!/usr/bin/env bash
# Write a Bash script that:

    # Creates the file /var/run/myscript.pid containing its PID
    # Displays To infinity and beyond indefinitely
    # Displays I hate the kill command when receiving a SIGTERM signal
    # Displays Y U no love me?! when receiving a SIGINT signal
    # Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# function handling SIGTERM and SIGQUIT signals
cleanup() {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 1
}

# function to handle SIGINT signal
handle_sigint() {
	echo "Y U no love me"
}

# Trap set ups for signals
trap 'cleanup' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

# getting pid of current process and storing it
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
